[package]
name = "medallyon/nascar"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
DataStore2 = "nidoxs/datastore2@1.4.0"
ZonePlus = "mattschrubb/zoneplus@3.2.0"
Janitor = "howmanysmall/janitor@1.14.1"
Roact = "roblox/roact@1.4.4"
Flipper = "reselim/flipper@2.0.0"
Rodux = "roblox/rodux@3.0.0"
RoactFlipper = "reselim/roact-flipper@2.0.0"
RoactRodux = "roblox/roact-rodux@0.5.1"
Sift = "csqrl/sift@0.0.2"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@1.2.1"
Knit = "sleitnick/knit@1.4.7"
Timer = "sleitnick/timer@1.1.2"
Input = "sleitnick/input@1.3.3"
Comm = "sleitnick/comm@0.3.1"
Component = "sleitnick/component@2.4.6"
EnumList = "sleitnick/enum-list@2.0.1"
Hooks = "kampfkarren/roact-hooks@0.5.0"
Trove = "sleitnick/trove@0.5.0"
Option = "sleitnick/option@1.0.4"
PID = "sleitnick/pid@1.0.2"
Shake = "sleitnick/shake@0.1.7"
Silo = "sleitnick/silo@0.1.1"
TableUtil = "sleitnick/table-util@1.2.0"
ProfileService = "nidoxs/profileservice@1.0.0"
